# Generated by Django 6.0.4 on 2026-04-23 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', '💵 Cash'), ('Card', '💳 Card'), ('Bank Transfer', '🏦 Bank Transfer'), ('Digital Wallet', '📱 Digital Wallet'), ('Loan/Credit', '🏦 Loan/Credit'), ('Other', '📝 Other')], default='Cash', max_length=50, null=True),
        ),
    ]
